version: '2'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oscars
